### ISSUE TITLE
Can the pretrained model suppot these waveform where target sound is far-field?

### ISSUE THREAD

**Issue by NewEricWang** [haoheliu/voicefixer#12]
I tried to use the test script for restoring my audio, but I obtained worse performance.
I suspect the model only supports target sound from close field.

**Comment by haoheliu** [comment]
Yes, some far-field voices may be treated as noise by the model. And during training, the distance between source and microphone is sampled in this Gaussian distribution: N(μ, σ2), μ = 2, σ = 4, which is usually not that far. So the model may become worse for the far-field voice.

**Comment by NewEricWang** [comment]
In my case, it works for test speech from 1 meter distance. But it seems worse performance for  test speech from 2 meter distance.  More distortion is found in processed target speech while less reverberation and noise are gained.
