### ISSUE TITLE
Unable to test, error in state_dict

### ISSUE THREAD

**Issue by yalharbi** [haoheliu/voicefixer#3]
Hello,

I am trying to test the code on a wav file. But I receive the following message:

RuntimeError: Error(s) in loading state_dict for VoiceFixer:
      Missing key(s) in state_dict: "f_helper.istft.ola_window". 
      Unexpected key(s) in state_dict: "f_helper.istft.reverse.weight", "f_helper.istft.overlap_add.weight". 

Which seemed to be caused by the following line in the code:
self._model = self._model.load_from_checkpoint(os.path.join(os.path.expanduser('~'), ".cache/voicefixer/analysis_module/checkpoints/epoch=15_trimed_bn.ckpt"))

Do you have an idea on how to resolve this issue?

**Comment by haoheliu** [comment]
It looks like torchlibrosa version you use is not 0.0.7. Please check your version of torchlibrosa.

**Comment by yalharbi** [comment]
Thanks. That fixed it.
