### ISSUE TITLE
Issue with defining Module

### ISSUE THREAD

**Issue by YTR76** [haoheliu/voicefixer#9]
I'm trying to make a Google Colab with the code of this one, but it somehow returned this error: NameError: name 'VoiceFixer' is not defined. I even actually defined VoiceFixer using one of the definitions from line 9 of base.py. So I changed the definition with line 93 of model.py, still got the same error. Do you know any fixes? If yes, reply.

**Comment by qiurui996** [comment]
> > > > I want to ask this: FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\59320.cache/voicefixer/synthesis_module/44100/model.ckpt-1490000_trimed.pt' please tell me how to do
> > > 
> > > 
> > > Normally the program will download checkpoint automatically when you import VoiceFixer or Vocoder. Could you please show me your code so that I can debug it? Alternatively, you can [download checkpoints](https://zenodo.org/record/5600188#.YXqhkPdByDU) by yourself and place them in the specified directory. And I'll test voicefixer on windows tomorrow (previously only tested on Linux and mac).
> > 
> > 
> > Thank you for your reply. I am a beginner in speech enhancement. It seems that chcekpoint cannot be downloaded automatically on the windows system. After manually adding it, it has been running normally. Thank you again for your help. In addition, I am currently working on a topic of repairing part of the speech distortion after speech enhancement. After reading your report on TechBeat, I may want to consider the size of the model as small as possible. I hope you can give me some suggestions if you have time.
> 
> Great to have your interest. It's totally possible to achieve a smaller model, which should be personalized to your need. We can have a voice discussion if you need.
Thank you very much for your answer, if it is convenient, can you add your WeChat for further communication

**Comment by haoheliu** [comment]
My WeChat number is xgdlhh0379

**Comment by haoheliu** [comment]
> > > > > I want to ask this: FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\59320.cache/voicefixer/synthesis_module/44100/model.ckpt-1490000_trimed.pt' please tell me how to do
> > > > 
> > > > 
> > > > Normally the program will download checkpoint automatically when you import VoiceFixer or Vocoder. Could you please show me your code so that I can debug it? Alternatively, you can [download checkpoints](https://zenodo.org/record/5600188#.YXqhkPdByDU) by yourself and place them in the specified directory. And I'll test voicefixer on windows tomorrow (previously only tested on Linux and mac).
> > > 
> > > 
> > > Thank you for your reply. I am a beginner in speech enhancement. It seems that chcekpoint cannot be downloaded automatically on the windows system. After manually adding it, it has been running normally. Thank you again for your help. In addition, I am currently working on a topic of repairing part of the speech distortion after speech enhancement. After reading your report on TechBeat, I may want to consider the size of the model as small as possible. I hope you can give me some suggestions if you have time.
> > 
> > 
> > Great to have your interest. It's totally possible to achieve a smaller model, which should be personalized to your need. We can have a voice discussion if you need.
> > Thank you very much for your answer, if it is convenient, can you add your WeChat for further communication

Sure, my wechat number is xgdlhh0379.
